name: Deployment CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Installing dependencies
        run: npm i --force

      # Build Next.js app
      - name: Building Next.js app
        run: npm run build

      - name: Adding Environment Variables
        run: |
          touch .env.local
          echo "${{ secrets.PROD_ENV }}" > .env.local

      - name: Deploying
        run: pm2 restart frontend
